apiVersion: v1
kind: Namespace
metadata:
  name: kafka
 
---
 
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  KAFKA_ADVERTISED_HOST_NAME: kafka
  KAFKA_ADVERTISED_PORT: "9092"
  KAFKA_CREATE_TOPICS: "topic1:1:1"
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_LOG_DIRS: /opt/kafka/data
 
---
 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pv-claim
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 
---
 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:5.5.1
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config
          volumeMounts:
            - name: kafka-pv-storage
              mountPath: /opt/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-pv-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
 
---
 
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
  clusterIP: None
 
---
 
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
  clusterIP: None
  clusterIPs:
    - None
    
...